[package]
name = "julix"
version = "0.0.7"
edition = "2024"
authors = ["Le Hung Quang Minh (furimeo) <224610210+furimeo@users.noreply.github.com>"]
license = "MIT"
description = "A dynamic, script-first language with a bytecode VM."

[[bin]]
name = "julix"
path = "src/main.rs"

[profile.release]
opt-level = 3
lto = true
strip = true
