#[derive(Debug, Clone)]
pub enum Expression {
    Int(i64),
    Str(String),
    Bool(bool),
    Ident(String),
    Add(Box<Expression>, Box<Expression>),
    Sub(Box<Expression>, Box<Expression>),
    Mul(Box<Expression>, Box<Expression>),
    Div(Box<Expression>, Box<Expression>),
    Mod(Box<Expression>, Box<Expression>),
    Eq(Box<Expression>, Box<Expression>),
    NotEq(Box<Expression>, Box<Expression>),
    Lt(Box<Expression>, Box<Expression>),
    Gt(Box<Expression>, Box<Expression>),
    LtEq(Box<Expression>, Box<Expression>),
    GtEq(Box<Expression>, Box<Expression>),
    And(Box<Expression>, Box<Expression>),
    Or(Box<Expression>, Box<Expression>),
    Not(Box<Expression>),
    Range(Box<Expression>, Box<Expression>),
    Call {
        callee: Box<Expression>,
        args: Vec<Expression>,
    },
}
