#[derive(Debug, Clone)]
pub enum Expression {
    Int(i64),
    Float(f64),
    Str(String),
    Bool(bool),
    Null,
    Ident(String),
    Add(Box<Expression>, Box<Expression>),
    Sub(Box<Expression>, Box<Expression>),
    Mul(Box<Expression>, Box<Expression>),
    Div(Box<Expression>, Box<Expression>),
    Mod(Box<Expression>, Box<Expression>),
    Eq(Box<Expression>, Box<Expression>),
    NotEq(Box<Expression>, Box<Expression>),
    Lt(Box<Expression>, Box<Expression>),
    Gt(Box<Expression>, Box<Expression>),
    LtEq(Box<Expression>, Box<Expression>),
    GtEq(Box<Expression>, Box<Expression>),
    And(Box<Expression>, Box<Expression>),
    Or(Box<Expression>, Box<Expression>),
    Not(Box<Expression>),
    Call {
        callee: Box<Expression>,
        args: Vec<Expression>,
    },
    FieldAccess {
        object: Box<Expression>,
        field: String,
    },
    MethodCall {
        object: Box<Expression>,
        method: String,
        args: Vec<Expression>,
    },
    Construct {
        type_name: String,
        fields: Vec<(String, Expression)>,
    },
    Bytes(Vec<u8>),
    List(Vec<Expression>),
    Map(Vec<(Expression, Expression)>),
    Index {
        object: Box<Expression>,
        index: Box<Expression>,
    },
    IndexSet {
        object: Box<Expression>,
        index: Box<Expression>,
        value: Box<Expression>,
    },
    FString(Vec<crate::lixer::lexer::token::FStrPart>),
}
